Squash all previous commits
A filesystem broken corrupted the git repo.
Previous commit messages are as follows:

commit cf8d1d34aa3bad3d5e73407d77b0df76afb16daf
Date:   Mon Feb 24 12:58:29 2025 +0800

    feat: Add `/model` command to switch LLM provider model

commit 16f23be83efd1874b8e949881c3f774e69524b9a
Date:   Mon Feb 24 11:43:53 2025 +0800

    refactor: Implement command pattern for agent commands

commit c60637699f5965a1ced0b507637d5339210825a0
Date:   Sat Feb 22 23:39:27 2025 +0800

    feat: Add general agent implementation

commit 61a83756a6dccdae3eed872bef98bd218846f585
Date:   Tue Feb 18 17:26:48 2025 +0800

    Use simplellm instead of litellm

commit 748321e281d6c0f5d9e58c71a5ca38ca6225b6af
Date:   Tue Feb 11 11:19:21 2025 +0800

    Improve README and prompts

commit 7e8a2492db374568d2b6154ca0a0976a2d5ccd47
Date:   Sat Feb 8 13:50:05 2025 +0800

    refactor: Replace langchain/langraph with direct litellm integration

commit dc746e1fddc6967b6482238c3cd97f19157b6c28
Date:   Fri Feb 7 14:22:28 2025 +0800

    ci: Add configuration/doc for testing and linting

commit 571c96f20d9f370e0d0b1ee538fd9f49c9b86c47
Date:   Thu Feb 6 19:53:59 2025 +0800

    feat: Use config.yaml to override agent configuration

commit b1acf571d75a1bcdc39c71a4715c2468a4cd7c32
Date:   Thu Feb 6 19:38:50 2025 +0800

    feat: Add model parameters to agent metadata and LLMBaseAgent

commit 548f4fad35785e17f5cb76d53a596e3763071821
Date:   Thu Feb 6 16:16:18 2025 +0800

    refactor: Extract graph streaming logic to LLMBaseAgent method

commit 569c019cd6d3d89435be5867ecf95bd2c9cacbfe
Date:   Thu Feb 6 12:52:09 2025 +0800

    refactor: Replace LLM function calls with `/save` command in agents

commit 70f5cf5fa5ab1758617327e168a76245a0df1aa4
Date:   Thu Feb 6 11:24:39 2025 +0800

    Collect some small improvements

    1. Replace `os` with `pathlib` for path handling
    2. use ~/.llmse6 as user directory
    3. add --set-env option
    4. draw langraph Graph with draw_png to get avoid network connection

commit e2520e59a2b3b7fc27e6de49d4b0cfac5cde54d0
Date:   Thu Jan 23 16:00:11 2025 +0800

    Update agent prompts
error: Could not read f3c5cc4f058c673490a0953933a8c10676c97220
fatal: Failed to traverse parents of commit b18cdef0b39366cd15724dbc955ad40c0faebf1f

commit 9777296950a513db44e513bbd71f6876412972cc
Date:   Thu Jan 23 16:09:12 2025 +0800

    feat: add observability provider option with langfuse support